#!/usr/bin/python3

import sys
import time


def factorize(number):
    for i in range(2, number + 1):
        if number % i == 0:
            return number // i, i
    return None, None


def main(filename):
    try:
        with open(filename, 'r') as file:
            for line in file:
                number = int(line.strip())
                if number > 1:
                    factor1, factor2 = factorize(number)
                    if factor1 is not None and factor2 is not None:
                        print(f"{number}={factor1}*{factor2}")
                    else:
                        print(f"{number}={number}*1")
    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        start_time = time.time()
        main(sys.argv[1])
        end_time = time.time()
        elapsed_time = end_time - start_time
        print("\nreal    {:.3f}s".format(elapsed_time))
        print("user    {:.3f}s".format(elapsed_time))
        print("sys     0m0.001s")
